version: '3'
services:
  db:
    image: postgres:9.6
    ports:
      - 5440:5432
    env_file:
      - .env
  redis:
    image: redis
    ports:
      - 6379:6379
  rails:
    build: .
    image: ma-rails
    command: sh -c 'cd /app/ma && bundle install && rails s -b 0.0.0.0'
    stdin_open: true
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    env_file:
      - .env
  sidekiq:
    image: ma-rails
    command: sh -c 'cd /app/ma && sidekiq'
    depends_on:
      - rails
      - redis
    env_file:
      - .env
